/* Independent overlay; input ticks are not guessed from candle OHLC or grouped L2 trades. */
(function(){'use strict';let layer=null,file=null,worker=null,domain=null;const bridge=window.__EDGELAB_FP4_BRIDGE__;if(!bridge)return;
const style=document.createElement('style');style.textContent=`#fp4-toggle{position:fixed;right:16px;top:48px;z-index:9001;background:#2783de;color:#fff;border:0;border-radius:8px;min-height:44px;padding:8px 16px;font:600 14px system-ui}#fp4-panel{position:fixed;right:16px;top:100px;z-index:9000;width:min(360px,calc(100vw - 32px));max-height:calc(100vh - 120px);overflow:auto;background:var(--pop-bg,#fff);color:var(--pop-text,#2c2c2b);border:1px solid var(--tb-border,#ddd);border-radius:8px;padding:16px;font:14px/1.5 system-ui;box-shadow:0 4px 12px #0001}#fp4-panel[hidden]{display:none}#fp4-panel label{display:block;margin-top:12px}#fp4-panel input:not([type=checkbox]),#fp4-panel button{width:100%;min-height:44px;border:1px solid #aaa;border-radius:6px;background:transparent;color:inherit;padding:8px;font:inherit}#fp4-panel input[type=file]{font-size:14px}#fp4-panel button{margin-top:12px;cursor:pointer}#fp4-panel small{display:block;font-size:14px;color:var(--axis-text,#555)}#fp4-status{margin:12px 0;padding:12px;background:#2783de15;overflow-wrap:anywhere}#fp4-panel :focus-visible,#fp4-toggle:focus-visible{outline:3px solid #2783de;outline-offset:2px}`;document.head.appendChild(style);
const btn=document.createElement('button');btn.id='fp4-toggle';btn.textContent='4 pasadas';btn.setAttribute('aria-expanded','false');document.body.appendChild(btn);
const panel=document.createElement('section');panel.id='fp4-panel';panel.hidden=true;panel.innerHTML=`<strong>Franja amplia · poco comercio</strong><small>Prototipo v0.2. Se detiene en la primera válida. No mide ventaja.</small><label>Ticks ordenados JSONL<input id="fp4-ticks" type="file" accept=".jsonl,.ndjson"></label><label>Inicio UTC (opcional)<input id="fp4-start" placeholder="2026-02-02T14:00:00Z"></label><label>Tick del activo<input id="fp4-tick" type="number" min="0.000001" step="any"></label><label>Ancho mínimo, ticks<input id="fp4-min" type="number" min="4" step="1" placeholder="30 para MNQ; transferir otros activos"></label><button id="fp4-search">Buscar / reiniciar manualmente</button><label>Capa ya calculada<input id="fp4-layer" type="file" accept=".json"></label><label><input id="fp4-clock" type="checkbox"> Confirmo la alineación raw ↔ reloj del bundle para esta revisión</label><small>No certifica reloj de ejecución. Sin confirmar, no se dibuja.</small><label>Offset de dibujo, segundos<input id="fp4-offset" type="number" value="0" step="1"></label><div id="fp4-status" role="status" aria-live="polite">Cargá ticks o una capa. Las velas solas no alcanzan.</div><button id="fp4-hide">Quitar capa / detener</button>`;document.body.appendChild(panel);
const el=id=>document.getElementById(id);const status=s=>{el('fp4-status').textContent=s;};function context(){return bridge.context();}
function validLayer(x){if(x.schema!=='edgelab.four_pass_sparse_layer/1'||!x.detector||typeof x.asset!=='string'||!(Number.isFinite(x.tick_size)&&x.tick_size>0))throw Error('SCHEMA_LAYER_REQUIRED');const z=x.detector.zone;if(!z)return;if(x.detector.status!=='STOPPED_FIRST_ZONE'||!Array.isArray(z.passes)||z.passes.length!==4||!Number.isSafeInteger(z.lo_tick)||!Number.isSafeInteger(z.hi_tick)||z.hi_tick<=z.lo_tick||!/^\d+$/.test(String(z.available_ns))||typeof z.available_ns!=='string'||!z.instrument||!z.contract)throw Error('INVALID_FROZEN_ZONE');for(const k of ['width_percentile','low_commerce_percentile','joint'])if(!Number.isFinite(z.assessment?.[k])||z.assessment[k]<0||z.assessment[k]>1)throw Error('INVALID_ZONE_SCORES');}
function redraw(){bridge.redraw();}btn.onclick=()=>{panel.hidden=!panel.hidden;btn.setAttribute('aria-expanded',String(!panel.hidden));const c=context();if(c){el('fp4-tick').value=c.tick_size||'';el('fp4-min').value=EdgeLabFourPass.DEFAULTS.width_minimums[String(c.instrument).toUpperCase()]||'';}};
function describe(){if(!layer)return;const d=layer.detector,z=d.zone;if(!z){status(d.status+' · '+d.seen+' ticks · '+d.completed4+' candidatas con cuatro. EOF no prueba ausencia.');return;}
 status('DETENIDO · 4/4 pasadas · tamaño P'+(z.assessment.width_percentile*100).toFixed(1)+' · poco comercio P'+(z.assessment.low_commerce_percentile*100).toFixed(1)+' · combinado '+(z.assessment.joint*100).toFixed(1)+' · X '+z.departure_ticks+' ticks');}
el('fp4-ticks').onchange=e=>{file=e.target.files[0]||null;};
el('fp4-search').onclick=()=>{if(worker)worker.terminate();layer=null;redraw();if(!file){status('Para reiniciar se requieren ticks JSONL, no una capa congelada.');return;}const c=context();if(!c){status('Cargá un activo primero.');return;}const size=Number(el('fp4-tick').value);if(!(size>0)){status('Tick inválido.');return;}let start='0';const text=el('fp4-start').value.trim();if(text){const ms=Date.parse(text);if(!Number.isFinite(ms)||!/(Z|[+-]\d\d:\d\d)$/.test(text)){status('Usá una fecha con zona UTC/Z explícita.');return;}start=(BigInt(ms)*1000000n).toString();}
 const floor=Number(el('fp4-min').value);if(!Number.isSafeInteger(floor)||floor<4){status('Falta un mínimo físico transferido para este activo.');return;}domain=c;worker=new Worker('four_pass_sparse_worker.js');status('Buscando; sin expiración de candidatas.');worker.onmessage=e=>{const m=e.data;if(m.type==='progress')status('Buscando · '+m.read+' ticks');else if(m.type==='error')status('ABSTAIN · '+m.message);else{layer={schema:'edgelab.four_pass_sparse_layer/1',asset:c.asset,tick_size:size,clock_status:'NOT_CERTIFIED',detector:m.detector};describe();redraw();worker.terminate();worker=null;}};worker.onerror=()=>status('Error del worker; no detección certificada');worker.postMessage({file:file,start_ns:start,configuration:{min_width_ticks:floor}});};
el('fp4-layer').onchange=async e=>{try{if(worker){worker.terminate();worker=null;}const x=JSON.parse(await e.target.files[0].text());validLayer(x);layer=x;domain=context();describe();redraw();}catch(err){layer=null;status('ABSTAIN · '+err.message);redraw();}};
el('fp4-clock').onchange=redraw;el('fp4-offset').onchange=redraw;
el('fp4-hide').onclick=()=>{if(worker)worker.terminate();worker=null;layer=null;status('Sin capa. Reinicio manual disponible con ticks.');redraw();};
window.__EDGELAB_FP4_OVERLAY__={draw:function(ctx,vr,w,h){if(!layer||!layer.detector.zone||!el('fp4-clock').checked)return;const c=context(),z=layer.detector.zone;if(!c||c.asset!==layer.asset||c.instrument!==z.instrument||c.contract!==z.contract||Number(c.tick_size)!==Number(layer.tick_size)){status('ABSTAIN · activo/contrato/tick de la capa no coincide');return;}
 const offset=Number(el('fp4-offset').value);if(!Number.isFinite(offset))return;const t=Number(BigInt(z.available_ns))/1e9+offset;if(t>vr.to)return;
 const x=bridge.x(t),y1=bridge.y(z.hi_tick*layer.tick_size),y2=bridge.y(z.lo_tick*layer.tick_size);if(![x,y1,y2].every(Number.isFinite)||x>=w||Math.max(y1,y2)<0||Math.min(y1,y2)>h)return;ctx.save();ctx.fillStyle='rgba(39,131,222,.10)';ctx.fillRect(Math.max(0,x),y1,w-Math.max(0,x),y2-y1);ctx.strokeStyle='#2783de';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(Math.max(0,x),y1);ctx.lineTo(w,y1);ctx.moveTo(Math.max(0,x),y2);ctx.lineTo(w,y2);ctx.stroke();ctx.fillStyle='#2783de';ctx.font='600 14px system-ui';ctx.fillText('4/4 · búsqueda detenida',Math.max(12,x+8),Math.max(18,y1-8));ctx.restore();}};
})();
